#!/usr/bin/env bash
# scripts/sync-state.sh — Generate ACC_CONFLICT_STATE.md for session auto-injection

set -e

WORKSPACE="${WORKSPACE:-${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}}"
STATE_FILE="$WORKSPACE/memory/conflict-state.json"
INJECT_FILE="$WORKSPACE/ACC_CONFLICT_STATE.md"
QUIET=false

[[ "${1:-}" == "--quiet" ]] && QUIET=true

if [[ ! -f "$STATE_FILE" ]]; then
  [[ "$QUIET" == false ]] && echo "⚡ No state file found. Run ./install.sh first." >&2
  exit 1
fi

# ── Read state ────────────────────────────────────────────────────────────────
LOAD=$(jq -r '.conflictLoad' "$STATE_FILE")
LOAD_FMT=$(printf "%.2f" "$LOAD")
ACTIVE=$(jq '.activeConflicts | length' "$STATE_FILE")
FLAGS=$(jq '.attentionFlags | length' "$STATE_FILE")
ZONES=$(jq '.uncertaintyZones | length' "$STATE_FILE")
UPDATED=$(jq -r '.lastUpdated' "$STATE_FILE")

# ── Determine load status and guidance ───────────────────────────────────────
LOAD_NUM=$(echo "$LOAD" | awk '{printf "%.4f", $1}')
if   awk "BEGIN{exit !($LOAD_NUM < 0.2)}";  then
  STATUS="🟢 Clear"
  GUIDANCE="Proceed confidently. No significant conflicts detected."
elif awk "BEGIN{exit !($LOAD_NUM < 0.4)}";  then
  STATUS="🟡 Low"
  GUIDANCE="Minor ambiguities present. Note them in responses where relevant."
elif awk "BEGIN{exit !($LOAD_NUM < 0.6)}";  then
  STATUS="🟠 Moderate"
  GUIDANCE="Some conflicts active. Verify key claims before responding."
elif awk "BEGIN{exit !($LOAD_NUM < 0.8)}";  then
  STATUS="🔴 Elevated"
  GUIDANCE="Multiple conflicts or significant ambiguity. Ask clarifying questions before proceeding."
else
  STATUS="🚨 Critical"
  GUIDANCE="High conflict load. State uncertainty explicitly. Do not proceed on assumptions."
fi

# ── Build active conflicts section ────────────────────────────────────────────
CONFLICTS_SECTION=""
if [[ "$ACTIVE" -gt 0 ]]; then
  CONFLICTS_SECTION=$(jq -r '
    .activeConflicts | to_entries[] |
    "- **[\(.value.type)]** \(.value.description)" +
    (if (.value.resolutionHint // "") != "" then "\n  - *Hint:* \(.value.resolutionHint)" else "" end)
  ' "$STATE_FILE")
fi

# ── Build attention flags section ─────────────────────────────────────────────
FLAGS_SECTION=""
if [[ "$FLAGS" -gt 0 ]]; then
  FLAGS_SECTION=$(jq -r '.attentionFlags[] | "- 📌 **\(.topic)** — \(.reason)"' "$STATE_FILE")
fi

# ── Build uncertainty zones section ──────────────────────────────────────────
ZONES_SECTION=""
if [[ "$ZONES" -gt 0 ]]; then
  ZONES_SECTION=$(jq -r '
    .uncertaintyZones | to_entries[] |
    "- **\(.key)** (level: \(.value.level | . * 100 | round)%) — \(.value.reason)"
  ' "$STATE_FILE")
fi

# ── Write ACC_CONFLICT_STATE.md ───────────────────────────────────────────────
cat > "$INJECT_FILE" << MDEOF
# ⚡ Anterior Cingulate — Conflict State

> Auto-generated by anterior-cingulate-memory. Do not edit manually.

## Conflict Load: $LOAD_FMT — $STATUS

**Guidance:** $GUIDANCE

| Metric | Value |
|--------|-------|
| Conflict Load | $LOAD_FMT |
| Active Conflicts | $ACTIVE |
| Attention Flags | $FLAGS |
| Uncertainty Zones | $ZONES |
| Last Updated | $UPDATED |

MDEOF

# Active conflicts block
if [[ "$ACTIVE" -gt 0 ]]; then
  cat >> "$INJECT_FILE" << MDEOF
## Active Conflicts

$CONFLICTS_SECTION

MDEOF
fi

# Attention flags block
if [[ "$FLAGS" -gt 0 ]]; then
  cat >> "$INJECT_FILE" << MDEOF
## Attention Flags

$FLAGS_SECTION

MDEOF
fi

# Uncertainty zones block
if [[ "$ZONES" -gt 0 ]]; then
  cat >> "$INJECT_FILE" << MDEOF
## Uncertainty Zones

$ZONES_SECTION

MDEOF
fi

cat >> "$INJECT_FILE" << 'MDEOF'
## Conflict Load Reference

| Load | Status | Behavior |
|------|--------|----------|
| < 0.20 | 🟢 Clear | Proceed confidently |
| 0.20–0.40 | 🟡 Low | Note ambiguities |
| 0.40–0.60 | 🟠 Moderate | Verify key claims |
| 0.60–0.80 | 🔴 Elevated | Ask before proceeding |
| > 0.80 | 🚨 Critical | Explicit caution required |
MDEOF

[[ "$QUIET" == false ]] && echo "⚡ ACC_CONFLICT_STATE.md updated (load: $LOAD_FMT, $STATUS)"

# Also regenerate the dashboard (every sibling module does this; this one was missing it)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/generate-dashboard.sh" ]; then
    "$SCRIPT_DIR/generate-dashboard.sh" 2>/dev/null || true
fi
