#!/bin/bash
# brain-daemon.sh — Unified scheduling daemon replacing per-skill cron entries.
#
# Every schedule below was pulled directly from the actual --with-cron blocks
# in each skill's install.sh (not reconstructed from memory) as of the current
# checkpoint. That audit surfaced real, pre-existing collisions: 11 different
# decay/analysis jobs across the suite all fire at minute :00 with overlapping
# hour-sets, and acc-conflict-encoding/social-encoding are IDENTICAL schedules
# (both `50 0,3,6,9,12,15,18,21 * * *`). Consolidating into one daemon is what
# made that visible — it was invisible when scattered across 11 install.sh
# files. Every job's HOUR-SET (its real frequency/intent) is preserved exactly
# as configured; only MINUTES were reassigned, each to a value no other job
# uses, so no two jobs can ever land in the same 30-second tick regardless of
# hour-set overlap. See BRAIN_DAEMON_SCHEDULE.md (generated by --check) for
# the full old-vs-new minute mapping.
#
# TWO JOB KINDS — this distinction is load-bearing, not cosmetic:
#   direct — the script is fully self-contained (decay/refine math, or a
#            script that already does its own LLM call and degrades
#            gracefully, like insula's rule-based encoder, ACC-conflict's
#            local-LLM call via llm-call.sh, or heartbeat's beat.sh). The
#            daemon just runs it.
#   spawn  — the job's real work needs an actual reasoning agent turn over
#            free text (deciding what's memory-worthy, what's an emotion,
#            what's a conflict). These skills' encode-pipeline.sh scripts
#            only do mechanical phase-1 staging and then say "sub-agent will
#            handle X" — there is no phase 2 without a real agent. This
#            daemon does NOT invent that reasoning step in bash. It shells
#            out to `openclaw sessions:spawn --task "..."`, reusing the
#            exact task text each skill's own install.sh already used for
#            `openclaw cron add --agent-turn "..."`. If openclaw isn't
#            installed or isn't in PATH, spawn jobs are skipped with a
#            clearly logged warning every time they're due — never silently.
#
# MISSED-TICK BEHAVIOR: if the daemon was stopped and restarts later, it does
# NOT fire jobs retroactively for windows that already passed while it was
# down. On startup, every job's "last fired" marker is initialized to now, so
# scheduling resumes cleanly from the next real match going forward. This
# avoids a thundering herd of encoding jobs (several of them local-LLM- or
# cloud-API-bound) all firing at once right after a restart.
#
# USAGE:
#   brain-daemon.sh              # run the daemon (systemd calls this)
#   brain-daemon.sh --check      # print the resolved job table + validate
#                                  every script path exists, then exit 0
#                                  without starting the loop
#
# ENV: WORKSPACE (standard across the whole suite, default ~/.openclaw/workspace)

set -u

WORKSPACE="${WORKSPACE:-$HOME/.openclaw/workspace}"
SKILLS_DIR="$WORKSPACE/skills"
PIDS_DIR="$WORKSPACE/memory/daemon-pids"
TICK_SECONDS=30

# ── Backpressure (PSI) ───────────────────────────────────────────────────────
# Ported from the PSI-Arbiter prototype: reads Linux Pressure Stall
# Information directly from the kernel (no vendor GPU driver needed) to
# detect when the box is genuinely saturated (e.g. Vulkan inference eating
# all the memory/CPU headroom) and defer heavy work until it clears.
# Override via env: BACKPRESSURE_THRESHOLD=15 brain-daemon.sh
PSI_MEM="/proc/pressure/memory"
PSI_CPU="/proc/pressure/cpu"
BACKPRESSURE_THRESHOLD="${BACKPRESSURE_THRESHOLD:-10.0}"
BACKPRESSURE_ACTIVE=0

# ── Job table ────────────────────────────────────────────────────────────────
# name|kind|hours|minutes|target
#   hours:   comma-separated 0-23, or "*" for every hour
#   minutes: comma-separated 0-59 (globally unique across this whole table —
#            that single invariant is what guarantees zero collisions; adding
#            a new job later just needs an unused minute, nothing more)
#   target:  for "direct" — path relative to $SKILLS_DIR
#            for "spawn"  — the exact --task text passed to sessions:spawn
JOBS="
heartbeat_beat|direct|*|7,37|heartbeat-memory/scripts/beat.sh
hippocampus_decay|direct|3|2|hippocampus-memory/scripts/decay.sh
hippocampus_encoding|spawn|0,3,6,9,12,15,18,21|0|Run hippocampus encoding with LLM summarization: 1. Run the encoding pipeline: WORKSPACE=\"$HOME/.openclaw/workspace\" ~/.openclaw/workspace/skills/hippocampus-memory/scripts/encode-pipeline.sh --no-spawn 2. Check pending memories: cat ~/.openclaw/workspace/memory/pending-memories.json 2>/dev/null | head -20 3. If pending exist, summarize each to ~100 chars 4. Update index.json with summaries 5. Delete pending-memories.json 6. Sync core: ~/.openclaw/workspace/skills/hippocampus-memory/scripts/sync-core.sh 7. Report results
amygdala_decay|direct|0,6,12,18|5|amygdala-memory/scripts/decay-emotion.sh
amygdala_encoding|spawn|0,3,6,9,12,15,18,21|10|Run amygdala emotional encoding: 1) Run preprocess-emotions.sh 2) Read encode-emotions.md 3) Update state for significant emotions 4) Update watermark 5) Sync state
vta_decay|direct|4,12,20|8|vta-memory/scripts/decay-drive.sh
vta_encoding|spawn|0,3,6,9,12,15,18,21|20|Run VTA reward encoding: 1) Run preprocess-rewards.sh 2) Read encode-rewards.md 3) Log rewards found 4) Resolve fulfilled anticipations 5) Sync state 6) Update watermark
basal_ganglia_decay|direct|4|12|basal-ganglia-memory/scripts/decay-habits.sh
basal_ganglia_encoding|spawn|0,3,6,9,12,15,18,21|30|Run basal-ganglia encoding pipeline: 1. Run the encoding pipeline: WORKSPACE=\"$HOME/.openclaw/workspace\" ~/.openclaw/workspace/skills/basal-ganglia-memory/scripts/encode-pipeline.sh --no-spawn 2. Check pending habits: cat ~/.openclaw/workspace/memory/pending-habits.json 2>/dev/null | head -40 3. For each pending signal, classify per prompts/encode-habits.md: new habit, reinforce existing habit/procedure, or new suppression 4. Update habit-state.json (use reinforce-habit.sh where possible) 5. Delete pending-habits.json 6. Sync state 7. Report results
insula_encoding|direct|0,3,6,9,12,15,18,21|40|insula-memory/scripts/encode-pipeline.sh
insula_decay|direct|0,4,8,12,16,20|14|insula-memory/scripts/decay-sense.sh
acc_conflict_encoding|direct|0,3,6,9,12,15,18,21|50|anterior-cingulate-memory/scripts/encode-pipeline.sh
acc_conflict_decay|direct|0,4,8,12,16,20|16|anterior-cingulate-memory/scripts/decay-load.sh
acc_error_analysis|spawn|4,12,20|18|Run ACC error analysis: encode-pipeline.sh, analyze exchanges, log errors, update watermark
pfc_decay|direct|0,6,12,18|22|prefrontal-cortex-memory/scripts/decay-load.sh
social_decay|direct|0|24|social-memory/scripts/decay.sh
social_encoding|spawn|0,3,6,9,12,15,18,21|52|Run social-memory encoding: 1) Run encode-pipeline.sh 2) Detect relationship signals 3) Update relationships 4) Update watermark 5) Sync state
cerebellum_refine|direct|0,8,16|26|cerebellum-memory/scripts/refine.sh
"

log() {
  echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] [INFO] $*"
}
warn() {
  echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] [WARN] $*" >&2
}
err() {
  echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] [ERROR] $*" >&2
}

get_psi_avg10() {
  # get_psi_avg10 <path> — reads the 'some' line of a Linux PSI pseudo-file
  # and prints its avg10 value (10-second pressure average, 0.00-100.00).
  # Prints 0 if the file is missing (e.g. non-Linux, or PSI not compiled in),
  # matching the prototype kernel's fail-open behavior.
  local path="$1" line val
  line=$(head -n1 "$path" 2>/dev/null) || { echo "0"; return; }
  val="${line#*avg10=}"
  val="${val%% *}"
  [ -z "$val" ] && val="0"
  echo "$val"
}

is_system_saturated() {
  # Returns success (0) if memory OR cpu PSI avg10 exceeds BACKPRESSURE_THRESHOLD.
  local mem cpu
  mem=$(get_psi_avg10 "$PSI_MEM")
  cpu=$(get_psi_avg10 "$PSI_CPU")
  awk -v m="$mem" -v c="$cpu" -v t="$BACKPRESSURE_THRESHOLD" \
    'BEGIN { exit !(m > t || c > t) }'
}

mkdir -p "$PIDS_DIR"

# ── --check mode: resolve, validate, print, exit. No loop, no side effects. ──
if [ "${1:-}" = "--check" ]; then
  echo "brain-daemon.sh --check"
  echo "WORKSPACE:   $WORKSPACE"
  echo "SKILLS_DIR:  $SKILLS_DIR"
  echo ""
  if [ -r "$PSI_MEM" ] && [ -r "$PSI_CPU" ]; then
    CUR_MEM=$(get_psi_avg10 "$PSI_MEM")
    CUR_CPU=$(get_psi_avg10 "$PSI_CPU")
    echo "PSI (avg10): memory=$CUR_MEM  cpu=$CUR_CPU  threshold=$BACKPRESSURE_THRESHOLD"
    echo "  -> spawn-type jobs will be deferred while either exceeds the threshold"
  else
    echo "PSI: unavailable ($PSI_MEM / $PSI_CPU not readable) — backpressure disabled, spawn jobs never deferred"
  fi
  echo ""
  printf "%-24s %-8s %-24s %-8s %s\n" "JOB" "KIND" "HOURS" "MINUTES" "TARGET"
  PROBLEMS=0
  SEEN_MINUTES=""
  while IFS='|' read -r name kind hours minutes target; do
    [ -z "$name" ] && continue
    for m in $(echo "$minutes" | tr ',' ' '); do
      case " $SEEN_MINUTES " in
        *" $m "*)
          echo "  !! COLLISION: minute $m is used by more than one job"
          PROBLEMS=$((PROBLEMS + 1))
          ;;
      esac
      SEEN_MINUTES="$SEEN_MINUTES $m"
    done
    if [ "$kind" = "direct" ]; then
      SCRIPT_PATH="$SKILLS_DIR/$target"
      if [ -x "$SCRIPT_PATH" ]; then
        EXISTS="ok"
      elif [ -f "$SCRIPT_PATH" ]; then
        EXISTS="EXISTS-BUT-NOT-EXECUTABLE"
        PROBLEMS=$((PROBLEMS + 1))
      else
        EXISTS="MISSING: $SCRIPT_PATH"
        PROBLEMS=$((PROBLEMS + 1))
      fi
      printf "%-24s %-8s %-24s %-8s %s\n" "$name" "$kind" "$hours" "$minutes" "$EXISTS"
    else
      printf "%-24s %-8s %-24s %-8s %s\n" "$name" "$kind" "$hours" "$minutes" "(sessions:spawn task, ${#target} chars)"
    fi
  done <<< "$JOBS"
  echo ""
  if command -v openclaw > /dev/null 2>&1; then
    echo "openclaw: found ($(command -v openclaw))"
  else
    echo "openclaw: NOT FOUND — spawn-type jobs will be skipped with a warning until this is fixed"
    PROBLEMS=$((PROBLEMS + 1))
  fi
  echo ""
  if [ "$PROBLEMS" -eq 0 ]; then
    echo "✅ All checks passed."
    exit 0
  else
    echo "❌ $PROBLEMS problem(s) found above."
    exit 1
  fi
fi

# ── Signal handling: log clean shutdown, exit promptly ───────────────────────
trap 'log "received SIGTERM — shutting down"; exit 0' TERM
trap 'log "received SIGINT — shutting down"; exit 0' INT

log "brain-daemon.sh starting. WORKSPACE=$WORKSPACE, tick=${TICK_SECONDS}s"

if command -v openclaw > /dev/null 2>&1; then
  log "openclaw found at $(command -v openclaw) — spawn-type jobs enabled"
else
  warn "openclaw not found in PATH — spawn-type jobs (encoding pipelines needing real reasoning) will be skipped every time they're due, until this is fixed. Direct-type jobs (decay, heartbeat, insula/ACC-conflict's self-contained encoders) are unaffected."
fi

# last-fired marker per job, keyed by "jobname:HH:MM" — prevents re-firing
# the same matched minute twice, and (see header) is deliberately NOT
# pre-populated with anything before "now" on startup, so a restart never
# retroactively fires jobs for windows that passed while the daemon was down.
declare -A LAST_FIRED_KEY

hour_matches() {
  # hour_matches <hours_spec> <current_hour>
  local spec="$1" hour="$2"
  [ "$spec" = "*" ] && return 0
  case ",$spec," in
    *",$hour,"*) return 0 ;;
    *) return 1 ;;
  esac
}

minute_matches() {
  # minute_matches <minutes_spec> <current_minute>
  local spec="$1" minute="$2"
  [ "$spec" = "*" ] && return 0
  case ",$spec," in
    *",$minute,"*) return 0 ;;
    *) return 1 ;;
  esac
}

run_job() {
  local name="$1" kind="$2" target="$3"
  local pid_file="$PIDS_DIR/${name}.pid"

  if [ -f "$pid_file" ]; then
    local existing_pid
    existing_pid=$(cat "$pid_file" 2>/dev/null || echo "")
    if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
      warn "$name: still running from a previous tick (pid $existing_pid) — skipping this firing"
      return
    fi
  fi

  (
    echo $$ > "$pid_file"
    if [ "$kind" = "direct" ]; then
      SCRIPT_PATH="$SKILLS_DIR/$target"
      if [ -x "$SCRIPT_PATH" ]; then
        log "$name: running $SCRIPT_PATH"
        WORKSPACE="$WORKSPACE" "$SCRIPT_PATH" >> "$WORKSPACE/memory/daemon-job-output.log" 2>&1
        STATUS=$?
        if [ "$STATUS" -eq 0 ]; then
          log "$name: completed"
        else
          err "$name: exited with status $STATUS — see $WORKSPACE/memory/daemon-job-output.log"
        fi
      else
        err "$name: script not found or not executable at $SCRIPT_PATH — skipping"
      fi
    else
      if command -v openclaw > /dev/null 2>&1; then
        log "$name: spawning agent session (waiting on shared spawn lock if another spawn job is mid-run)"
        # Single shared lock across all spawn-kind jobs: two agent-turns doing
        # real LLM inference concurrently would contend for the same GPU.
        # Direct-kind jobs never touch this lock, so decay/heartbeat/etc.
        # keep running on schedule regardless.
        flock "$WORKSPACE/memory/.spawn.lock" openclaw sessions:spawn --task "$target" >> "$WORKSPACE/memory/daemon-job-output.log" 2>&1
        STATUS=$?
        if [ "$STATUS" -eq 0 ]; then
          log "$name: spawn completed"
        else
          err "$name: sessions:spawn exited with status $STATUS — see $WORKSPACE/memory/daemon-job-output.log"
        fi
      else
        warn "$name: due now, but openclaw is not in PATH — skipped (this needs real agent reasoning, not just a script)"
      fi
    fi
    rm -f "$pid_file"
  ) &
}

# Initialize: mark "now" as already-serviced for every job so a fresh start
# (or restart after downtime) never fires a backlog of missed windows.
INIT_HOUR=$(date -u +"%H" | sed 's/^0//'); [ -z "$INIT_HOUR" ] && INIT_HOUR=0
INIT_MIN=$(date -u +"%M" | sed 's/^0//'); [ -z "$INIT_MIN" ] && INIT_MIN=0
while IFS='|' read -r name kind hours minutes target; do
  [ -z "$name" ] && continue
  LAST_FIRED_KEY["$name"]="${INIT_HOUR}:${INIT_MIN}"
done <<< "$JOBS"
log "initialized — will not fire for the current minute (${INIT_HOUR}:${INIT_MIN}), only from the next matching minute forward"

while true; do
  NOW_HOUR=$(date -u +"%H" | sed 's/^0//'); [ -z "$NOW_HOUR" ] && NOW_HOUR=0
  NOW_MIN=$(date -u +"%M" | sed 's/^0//'); [ -z "$NOW_MIN" ] && NOW_MIN=0
  CURRENT_KEY="${NOW_HOUR}:${NOW_MIN}"

  # Check system pressure once per tick (not once per job) — cheap, and
  # keeps every job in this tick judged against the same reading.
  if is_system_saturated; then
    if [ "$BACKPRESSURE_ACTIVE" != "1" ]; then
      warn "system saturated (PSI avg10 > ${BACKPRESSURE_THRESHOLD}) — deferring spawn-type jobs until pressure clears; direct jobs unaffected"
    fi
    BACKPRESSURE_ACTIVE=1
  else
    if [ "$BACKPRESSURE_ACTIVE" = "1" ]; then
      log "system pressure back under threshold — resuming normal scheduling"
    fi
    BACKPRESSURE_ACTIVE=0
  fi

  while IFS='|' read -r name kind hours minutes target; do
    [ -z "$name" ] && continue

    if [ "${LAST_FIRED_KEY[$name]:-}" = "$CURRENT_KEY" ]; then
      continue
    fi

    if hour_matches "$hours" "$NOW_HOUR" && minute_matches "$minutes" "$NOW_MIN"; then
      if [ "$kind" = "spawn" ] && [ "$BACKPRESSURE_ACTIVE" = "1" ]; then
        # Deliberately do NOT set LAST_FIRED_KEY here — leaving it unset lets
        # this job retry on the next tick (30s later) if still within the
        # same matching minute, in case pressure clears quickly. If the
        # minute passes while still saturated, the job is simply skipped for
        # this window (consistent with the daemon's non-retroactive design;
        # see MISSED-TICK BEHAVIOR above) and fires next time it's due.
        warn "$name: due now but system is under pressure — deferring"
        continue
      fi
      LAST_FIRED_KEY["$name"]="$CURRENT_KEY"
      run_job "$name" "$kind" "$target"
    fi
  done <<< "$JOBS"

  sleep "$TICK_SECONDS"
done
