#!/bin/bash
# create-module.sh — Self-mod new-module creation (Initiative 11 / M6 precursor).
#
# Takes a proposal's `new_module` field (name, capabilities, skeleton_script)
# and generates a full skill directory with capability-manifest.json, SKILL.md,
# a skeleton script, and registers it in the capability registry.
#
# Usage:
#   create-module.sh --proposal PATH.json --suite-root PATH [--dry-run]
#
# Proposal `new_module` shape:
#   { "name": "foo-memory", "capabilities": ["bar"], "description": "...",
#     "base_script": "scripts/encode-pipeline.sh",
#     "state_file": "memory/foo-state.json" }

set -euo pipefail

PROPOSAL=""
SUITE_ROOT=""
DRY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --proposal) PROPOSAL="$2"; shift 2 ;;
    --suite-root) SUITE_ROOT="$2"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    *) shift ;;
  esac
done

[ -n "$PROPOSAL" ] || { echo "create-module.sh: --proposal required" >&2; exit 2; }
[ -n "$SUITE_ROOT" ] || { echo "create-module.sh: --suite-root required" >&2; exit 2; }
[ -f "$PROPOSAL" ] || { echo "create-module.sh: proposal file not found: $PROPOSAL" >&2; exit 1; }

NM=$(jq -r '.new_module // empty' "$PROPOSAL" 2>/dev/null)
[ -n "$NM" ] || { echo '{"error":"no new_module field in proposal"}' >&2; exit 1; }

NAME=$(echo "$NM" | jq -r '.name // empty')
[ -n "$NAME" ] || { echo '{"error":"new_module.name is required"}' >&2; exit 1; }

CAPS=$(echo "$NM" | jq -c '.capabilities // []')
DESC=$(echo "$NM" | jq -r '.description // "Auto-generated module"')
STATE_FILE=$(echo "$NM" | jq -r '.state_file // "memory/'"$NAME"'-state.json"')

SKILL_DIR="$SUITE_ROOT/skills/$NAME"
MANIFEST="$SKILL_DIR/capability-manifest.json"

if [ "$DRY" -eq 0 ]; then
    mkdir -p "$SKILL_DIR/scripts" "$SKILL_DIR/prompts"

    # ── Capability manifest ──────────────────────────────────────────────────
    jq -n \
        --arg name "$NAME" \
        --argjson caps "$CAPS" \
        --arg desc "$DESC" \
        --arg state "$STATE_FILE" \
    '{
        schema: 1,
        module: $name,
        version: "0.1.0",
        description: $desc,
        immutable: false,
        capabilities: $caps,
        inputs: [
            { name: "workspace_events", type: "event", source: "workspace/events" },
            { name: "module_state", type: "state_file", source: $state, required: false }
        ],
        outputs: [
            { name: "module_state", type: "state_write", target: $state }
        ],
        side_effects: ["writes_shared_state"],
        dependencies: [],
        tests: []
    }' > "$MANIFEST"

    # ── SKILL.md ─────────────────────────────────────────────────────────────
    cat > "$SKILL_DIR/SKILL.md" << MDEOF
# $NAME

$DESC

## Capabilities
$(echo "$CAPS" | jq -r '.[]' | sed 's/^/- /')

## State
- \`$STATE_FILE\` — module state

## Created
Auto-generated by self-mod pipeline on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
MDEOF

    # ── install.sh (standard lifecycle contract) ─────────────────────────────
    cat > "$SKILL_DIR/install.sh" << 'SHEOF'
#!/bin/bash
# install.sh — Auto-generated skill installer
if [ "${1:-}" = "--uninstall" ]; then
    THIS_DIR="$(cd "$(dirname "$0")" && pwd)"
    WS="${WORKSPACE:-$HOME/.hermes/workspace}"
    for CAND in "$THIS_DIR/../../core/skill-init/skill-cleanup.sh" \
                "$THIS_DIR/../../../core/skill-init/skill-cleanup.sh"; do
        if [ -x "$CAND" ]; then
            exec "$CAND" --skill "$THIS_DIR" --workspace "$WS" "${2:-}"
        fi
    done
    echo "uninstall: skill-cleanup.sh not found." >&2
    exit 1
fi
set -euo pipefail
WS="${WORKSPACE:-$HOME/.hermes/workspace}"
mkdir -p "$WS/memory"
chmod +x "$(dirname "$0")/scripts/"*.sh 2>/dev/null || true
echo "✅ $NAME initialized."
SHEOF
    chmod +x "$SKILL_DIR/install.sh"

    echo "✅ Created module: $NAME at $SKILL_DIR"
    echo "   manifest: $MANIFEST"
else
    echo "[dry-run] Would create module $NAME at $SKILL_DIR"
fi

exit 0